# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[font]
size = 14

[font.normal]
#family = "ComicShannsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"

[window.padding]
x = 7
y = 0

[shell]
program = "/bin/bash"

[env]
TERM = "xterm-256color"

[cursor]
unfocused_hollow = true
vi_mode_style = "None"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "#ff00ff"
