#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# create directories
export XDG_CONFIG_HOME="$HOME"/.config

mkdir -p "$HOME"/Projects

mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
mkdir -p "$XDG_CONFIG_HOME"/newsboat
mkdir -p "$XDG_CONFIG_HOME"/wezterm

# Symbolic links

ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml

ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc

ln -sf "$PWD/.zshrc" "$HOME"/.zshrc

ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/newsboat/config" "$XDG_CONFIG_HOME"/newsboat/config
ln -sf "$PWD/newsboat/urls" "$XDG_CONFIG_HOME"/newsboat/urls
ln -sf "$PWD/starship.toml" "$XDG_CONFIG_HOME"/starship.toml

ln -sf "$PWD/wezterm.lua" "$XDG_CONFIG_HOME"/wezterm/wezterm.lua
