#!/bin/bash

# Navigate to the root of a Git repository
cd_to_git_root() {
  # Navigate up the directory hierarchy until you find a .git directory
  local dir="$(git rev-parse --show-toplevel 2>/dev/null)"
  echo $dir 
  if [ -n "$dir" ]; then
    cd "$dir" || exit
  else
    echo "Not inside a Git repository."
  fi
}

cd_to_git_root

